INSERT INTO business_categories (name, slug) VALUES
('Supermarket & General Stores', 'supermarket-general-stores'),
('Groceries & Food', 'groceries-food'),
('Clothing & Fashion', 'clothing-fashion'),
('Shoes & Footwear', 'shoes-footwear'),
('Bags & Luggage', 'bags-luggage'),
('Jewelry & Accessories', 'jewelry-accessories'),
('Beauty & Cosmetics', 'beauty-cosmetics'),
('Health & Personal Care', 'health-personal-care'),
('Electronics', 'electronics'),
('Phones & Tablets', 'phones-tablets'),
('Computers & Accessories', 'computers-accessories'),
('Home Appliances', 'home-appliances'),
('Furniture', 'furniture'),
('Home & Kitchen', 'home-kitchen'),
('Hardware & Tools', 'hardware-tools'),
('Building & Construction Materials', 'building-construction-materials'),
('Plumbing & Electrical', 'plumbing-electrical'),
('Automotive & Motorcycles', 'automotive-motorcycles'),
('Bicycles & Cycling', 'bicycles-cycling'),
('Sports & Fitness', 'sports-fitness'),
('Outdoor & Camping', 'outdoor-camping'),
('Toys & Games', 'toys-games'),
('Baby & Kids', 'baby-kids'),
('Books & Stationery', 'books-stationery'),
('Office & Business Supplies', 'office-business-supplies'),
('School Supplies', 'school-supplies'),
('Pet Supplies', 'pet-supplies'),
('Agriculture & Farming', 'agriculture-farming'),
('Garden & Outdoor', 'garden-outdoor'),
('Industrial & Commercial Equipment', 'industrial-commercial-equipment'),
('Machinery & Equipment', 'machinery-equipment'),
('Cleaning & Household Supplies', 'cleaning-household-supplies'),
('Hardware & Home Improvement', 'hardware-home-improvement'),
('Music & Musical Instruments', 'music-musical-instruments'),
('Photography & Video', 'photography-video'),
('Computers & Gaming', 'computers-gaming'),
('Entertainment & Media', 'entertainment-media'),
('Gifts & Flowers', 'gifts-flowers'),
('Art & Crafts', 'art-crafts'),
('Watches', 'watches'),
('Travel & Travel Accessories', 'travel-travel-accessories'),
('Safety & Security', 'safety-security'),
('Medical & Healthcare Supplies', 'medical-healthcare-supplies'),
('Religious & Cultural Products', 'religious-cultural-products'),
('Automotive Parts & Accessories', 'automotive-parts-accessories'),
('Motorcycles & Spare Parts', 'motorcycles-spare-parts'),
('Tyres & Batteries', 'tyres-batteries'),
('Fuel & Energy Products', 'fuel-energy-products'),
('Packaging & Printing', 'packaging-printing'),
('Furniture & Interior Decor', 'furniture-interior-decor'),
('Mattresses & Bedding', 'mattresses-bedding'),
('Lighting & Electrical', 'lighting-electrical'),
('Curtains & Home Textiles', 'curtains-home-textiles'),
('Kitchenware & Cookware', 'kitchenware-cookware'),
('Food & Beverages', 'food-beverages'),
('Bakery & Confectionery', 'bakery-confectionery'),
('Meat & Poultry', 'meat-poultry'),
('Fish & Seafood', 'fish-seafood'),
('Fruits & Vegetables', 'fruits-vegetables'),
('Alcoholic Beverages', 'alcoholic-beverages'),
('Baby Food & Products', 'baby-food-products'),
('Second-Hand & Used Goods', 'second-hand-used-goods'),
('Wholesale & Bulk Goods', 'wholesale-bulk-goods'),
('Luxury & Premium Goods', 'luxury-premium-goods'),
('Local & Handmade Products', 'local-handmade-products'),
('Other', 'other')
ON CONFLICT (name) DO NOTHING;
