-- ============================================================
--  SUPER ADMIN SEED
--  Location: migrations/sql/20260918-super-admin-seed.sql
--
--  Purpose:
--   Creates one super admin account so you can log in at
--   /admin.html. It is a one-shot seed: if a super admin
--   already exists, the file does nothing.
--
--  Login credentials created by this file:
--    email:    admin@bidhaalink.com
--    password: ChangeMe123!
--    username: superadmin
--    role:     super_admin
--
--  IMPORTANT — change the password immediately after your
--  first login. This file is only a bootstrap. The password
--  below is a bcrypt hash of "ChangeMe123!" with cost 10.
--
--  The hash is generated by:
--    node -e "console.log(require('bcrypt').hashSync('ChangeMe123!', 10))"
--  If you want a different password, run that command with
--  your own password and replace the hash below.
--
--  Idempotent:
--   The guard clause below checks whether any super_admin
--   already exists. If one does, the whole insert is skipped.
--   Running the migration a second time changes nothing.
-- ============================================================

DO $$
DECLARE
    existing_super_admin_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO existing_super_admin_count
    FROM admin_users
    WHERE role = 'super_admin';

    IF existing_super_admin_count > 0 THEN
        RAISE NOTICE 'A super admin already exists (% account(s)). Seed skipped.', existing_super_admin_count;
        RETURN;
    END IF;

    -- Bcrypt hash of "ChangeMe123!" at cost 10.
    -- Replace this hash with your own if you want a different password.
    INSERT INTO admin_users (username, email, password, role)
    VALUES (
        'superadmin',
        'admin@bidhaalink.com',
        '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
        'super_admin'
    );

    RAISE NOTICE 'Super admin created: admin@bidhaalink.com / ChangeMe123!';
    RAISE NOTICE 'Log in at /admin.html and change the password immediately.';
END $$;

-- ============================================================
--  VERIFY
-- ============================================================

DO $$
DECLARE
    super_admin_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO super_admin_count
    FROM admin_users
    WHERE role = 'super_admin';

    RAISE NOTICE 'super_admin accounts in database: %', super_admin_count;

    IF super_admin_count >= 1 THEN
        RAISE NOTICE 'You can now log in at /admin.html';
    ELSE
        RAISE NOTICE 'No super admin found. Please check the migration output.';
    END IF;
END $$;